services:
  feature-3dgs:
    container_name: feature_3dgs_test
    image: feature_3dgs:test
    build:
      context: .
      dockerfile: Dockerfile3
    tty: true
    ports:
      - 6009:6009
    volumes:
      - /home/dang/git/feature-3dgs/src:/workspace/feature-3dgs
      - /home/dang/data:/workspace/data
      - /home/dang/checkpoints/sam:/workspace/feature-3dgs/encoders/sam_encoder/checkpoints
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:rw
    environment:
      - DISPLAY=$DISPLAY
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [compute,utility,graphics]

